#!/usr/bin/env bash
# scripts/06_paper/build_paper_html.sh
#
# Concatenate the drafted markdown sections, splice in figures, and render
# the whole thing as a single standalone HTML file using the policy-memo
# structure (§2 motivation -> §3 landscape -> §4 findings -> Appendix A,
# Appendix B). Run after render_tables_html.R.
#
# Run: bash scripts/06_paper/build_paper_html.sh

set -e
cd "$(dirname "$0")/../.."   # project root

OUT_DIR="output/paper"
mkdir -p "$OUT_DIR"

COMBINED_MD="$OUT_DIR/combined.md"
HTML_OUT="$OUT_DIR/paper_draft.html"

# Build the combined markdown.
{
  cat <<'EOF'
---
title: "Digital Payments and Financial Inclusion in India"
subtitle: "A State-Level Look at the Early and Mature UPI Eras"
author: "Hari Dharshini Koundinya Swaminathen"
---

EOF

  cat paper/sections/01_executive_summary.md
  echo ""

  cat paper/sections/02_motivation.md
  echo ""

  cat paper/sections/03_landscape.md
  echo ""
  echo '## Figure 2 — State ranking by per-capita UPI use, most recent twelve months (Feb 2025 – Jan 2026)'
  echo ""
  echo '![](../figures/fig2_state_ranking_w3.png)'
  echo ""
  echo '## Table 1 — Descriptive statistics, most recent twelve months (Feb 2025 – Jan 2026)'
  echo ""
  cat output/tables/md/tab1_descriptive.md
  echo ""
  echo '## Figure 4 — Cross-state dispersion in per-capita UPI, Apr 2023 – Jan 2026'
  echo ""
  echo '![](../figures/fig4_convergence.png)'
  echo ""

  cat paper/sections/04_findings.md
  echo ""

  cat paper/sections/05_policy_implications.md
  echo ""

  cat paper/sections/06_conclusion.md
  echo ""

  cat paper/sections/AA_appendix_a_methodology.md
  echo ""

  cat paper/sections/AB_appendix_b_data_construction.md
  echo ""
} > "$COMBINED_MD"

# Render to standalone HTML.
pandoc "$COMBINED_MD" \
  --from markdown+raw_html+grid_tables+pipe_tables \
  --to html5 \
  --standalone \
  --css="paper.css" \
  --output "$HTML_OUT"

# Stylesheet next to the HTML.
cat > "$OUT_DIR/paper.css" <<'CSS'
body {
  font-family: "Times New Roman", "Liberation Serif", "Nimbus Roman", Times, serif;
  max-width: 760px;
  margin: 2em auto;
  padding: 0 1.5em;
  line-height: 1.5;
  color: #1a1a1a;
  text-align: justify;
  hyphens: auto;
  -webkit-hyphens: auto;
}
h1 {
  font-family: "Times New Roman", Times, serif;
  font-size: 1.6em;
  margin-top: 1.8em;
  margin-bottom: 0.8em;
  font-weight: bold;
  text-align: left;
}
h2 {
  font-family: "Times New Roman", Times, serif;
  font-size: 1.2em;
  margin-top: 1.6em;
  margin-bottom: 0.5em;
  font-weight: bold;
  font-style: italic;
  text-align: left;
}
h3 {
  font-size: 1.05em;
  margin-top: 1.3em;
  text-align: left;
}
p { margin: 0 0 0.8em 0; }
img { max-width: 100%; height: auto; display: block; margin: 1.5em auto; }
table {
  border-collapse: collapse;
  margin: 1.5em auto;
  font-size: 0.92em;
  font-family: "Times New Roman", Times, serif;
}
table, th, td { border: 1px solid #888; padding: 0.4em 0.7em; }
th { background: #f0f0f0; font-weight: bold; }
blockquote { border-left: 3px solid #999; padding-left: 1em; color: #444; font-style: italic; }
code { font-family: "Menlo", monospace; font-size: 0.92em; background: #f5f5f5; padding: 0.1em 0.3em; }
.paper-table { font-size: 0.88em; }
hr { border: none; border-top: 1px solid #ccc; margin: 2.5em 0; }
sup { font-size: 0.75em; }

/* Title block (h1.title generated by pandoc YAML metadata) */
header.title-block-header h1.title {
  font-size: 1.8em;
  text-align: center;
  margin-top: 0.5em;
  margin-bottom: 0.3em;
}
header.title-block-header p.subtitle,
header.title-block-header p.author,
header.title-block-header p.date {
  text-align: center;
  margin: 0.2em 0;
  font-style: italic;
}
CSS

echo ""
echo "Wrote $HTML_OUT"
echo "Wrote $OUT_DIR/paper.css"
echo "Wrote $COMBINED_MD"
echo ""
echo "Open in browser:  open $HTML_OUT"
