# scripts/05_tables_figures/tab1_descriptive_stats.R
#
# Table 1 (paper): Descriptive statistics for the most recent 12 months (Feb 2025 – Jan 2026)
# panel. One row per variable; columns: N, mean, SD, min, max, and the
# population-weighted India-wide value (the figure a policy reader would
# expect to see when they ask "what's the national level?").
#
# Variables ordered: dependent variable first, then the headline
# regressors (NSDP, internet, urban, PMJDY, branches), then literacy
# (which is in the appendix spec only).
#
# Outputs:
#   output/tables/tab1_descriptive_stats.tex
#   output/tables/tab1_descriptive_stats.txt
#
# Run: Rscript scripts/05_tables_figures/tab1_descriptive_stats.R

if (!file.exists("CLAUDE.md")) stop("Run from project root.", call. = FALSE)
suppressPackageStartupMessages({
  library(dplyr); library(readr); library(tibble); library(knitr)
})

panel <- read_csv("data/processed/part2_panel_3year.csv",
                  show_col_types = FALSE) |>
  filter(year_window == "2025-26r")

# Variable specification: column name, paper-ready label, units, decimals
# for display, and a transform applied before formatting (most are
# identity; share_urban is multiplied by 100 to display as a percentage;
# pmjdy_per_adult is multiplied by 100 to display as accounts per 100 adults).
var_spec <- tribble(
  ~var,                     ~label,                                                                  ~unit,             ~decimals, ~scale,
  "per_capita_upi",         "Per-capita UPI transactions (Feb 2025 – Jan 2026 avg)",                 "per person/month", 1,         1,
  "per_capita_nsdp",        "Per-capita NSDP (latest available, constant 2011-12 prices)",           "INR",              0,         1,
  "internet_density",       "Internet subscribers (31-Mar-2025, latest TRAI release)",               "per 100 persons",  1,         1,
  "share_urban",            "Urban population share (interpolated to 2025)",                         "%",                1,         100,
  "pmjdy_per_adult",        "PMJDY beneficiaries per adult (snapshot 13-Dec-2025)",                  "accounts / adult", 2,         1,
  "bank_offices_per_100k",  "Bank offices per 100,000 population (31-Dec-2025)",                     "per 100k pop",     1,         1,
  "literacy",               "Literacy rate, persons 7+ (FY 2023-24, appendix only)",                 "%",                1,         1
)

# Population for the India-wide weighted averages.
pop <- panel$population

summarise_one <- function(var, label, unit, decimals, scale) {
  x  <- panel[[var]] * scale
  ok <- !is.na(x)
  fmt <- function(z) formatC(z, digits = decimals, format = "f", big.mark = ",")
  india <- weighted.mean(x[ok], w = pop[ok])
  tibble(
    Variable      = label,
    Unit          = unit,
    N             = as.integer(sum(ok)),
    Mean          = fmt(mean(x[ok])),
    SD            = fmt(sd(x[ok])),
    Min           = fmt(min(x[ok])),
    Max           = fmt(max(x[ok])),
    `India (pop-wt.)` = fmt(india)
  )
}

tab <- purrr::pmap_dfr(var_spec, summarise_one)

# -------- Console + plain-text output for review -----------------------------
cat("\n=== Table 1: Descriptive statistics, most recent 12 months (Feb 2025 – Jan 2026) ===\n\n")
print(tab, n = nrow(tab))

if (!dir.exists("output/tables")) dir.create("output/tables", recursive = TRUE)
writeLines(c(
  "Table 1: Descriptive statistics, most recent 12 months (Feb 2025 – Jan 2026) panel.",
  "Sample: 36 states/UTs (N varies by variable due to missingness).",
  "India column: weighted by mid-period population.",
  "",
  paste(capture.output(print(tab, n = nrow(tab))), collapse = "\n")
), "output/tables/tab1_descriptive_stats.txt")

# -------- LaTeX output -------------------------------------------------------
latex <- knitr::kable(
  tab, format = "latex", booktabs = TRUE, escape = TRUE, linesep = "",
  caption = "Descriptive statistics, most recent 12 months (Feb 2025 – Jan 2026) panel.",
  align = c("l", "l", "r", "r", "r", "r", "r", "r")
)
writeLines(c(
  "% Generated by scripts/05_tables_figures/tab1_descriptive_stats.R",
  "% Source: data/processed/part2_cross_section_fy2425.csv",
  as.character(latex)
), "output/tables/tab1_descriptive_stats.tex")

message("\nWrote output/tables/tab1_descriptive_stats.{tex,txt}")
